---
language: node_js
node_js:
  - "stable"
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
addons:
  code_climate:
    repo_token: f147df85a17a09bed8704ba2a3172b9a45519d0adb385b689bc2a323222f0efd
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < test/unit/coverage/lcov.info
