---
language: node_js
node_js:
  - "stable"
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
addons:
  code_climate:
    repo_token: 9c5ae1de2fd177779f491a14e2ed72125a9a0bab06a926ad69371b99b4129bfd
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < test/unit/coverage/lcov.info
