language: node_js
node_js:
- stable
sudo: required
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
addons:
  code_climate:
    repo_token: 9c5ae1de2fd177779f491a14e2ed72125a9a0bab06a926ad69371b99b4129bfd
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < test/unit/coverage/lcov.info
deploy:
  provider: npm
  email: pinpon.ikeda@gmail.com
  api_key:
    secure: XhMqOzJ6ipH7xkmuzXI9apBxe4Fjgi1p2yf4kjoaCph5EPLEXorY4v7sJFidjQEfPDKbx6XtpzUEt/5I48cvBeBHt/foBZvoppY6WGQDEB4fgYrl+4tpMc4fjYXyzWbQTZ4veoHgx9eWv/WO4Nf/vz3/fUgViwrMncr5omfwcgS9iUKHtWdKjpMMTv5VhNMXMGYY5l8d5CQLgBMfFIJf+dx313G5reYco/OdC5wkn4P4Y0w4mKKDXTE43iu7liR9M8wFVNYwA8Fd3V5RZHW9bzSqRIq8QmxQ5B1jL1y5H+38901EqTdKYh/wtyD2ZuK+81yZ6BXouZ+VyUaZh3juzC/lwACLULnG2549ayb5CfrUc+7VJCzMjgNXMw/tns5VPLWH3YA3HPIAyUTpXL2S7MAcgcooBChOsrq91vwW60RX0J4YALZZQqzB2BRKc4FFgnvAVvNQoeQlFxX24D391bumm6+1pgQ79GlrlPqoBIJ7zDVTdbjcwWNvLia/se8ZG2+R3USim/qf9s0zjOYq0FhXwxeIhDwRqrgbvw+RYv9itCdx71i95cnw0DjzR4LHFXlnXBbnCrKydGC9FyGuaXZ05P6WkADZj/ZzSGZHcR1VdjSoJxjiNdnTmEjBXJO3hvjCanEEyvYzUKUTgBL2T8njiQxA9fIIX+mlieYbLa8=
  on:
    tags: true
